# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-12 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
