# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0004_auto_20180314_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='dx',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
