# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-14 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0005_auto_20180314_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.TextField(blank=True),
        ),
    ]
