# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0006_auto_20180314_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='dx',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_recibo',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='fecha_relacion',
        ),
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nss',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.TextField(blank=True),
        ),
    ]
