# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-20 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buscador', '0007_auto_20180319_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='especialidad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='fecha_cita',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='lugar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nombre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='nss',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cita',
            name='status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
